language : node_js
node_js :
    - "0.10"
    - "0.12"
    - "4"
    - "5"
before_install:
    - npm install -g npm
before_script :
    - npm install -g grunt-cli
after_script:
    - npm run coveralls
sudo: false
